import './App.css';
import Answer from './Answer';
import { useState } from 'react';

//create random numbers
const serverNum = Math.floor(Math.random()*10) +1;


function App()
{
  //create state
  const [term, setTerm] = useState("")
  //getting the number from input feild 
  const handleInputvalue= (a) =>{
      setTerm(a.target.value)
  }
  //term is user input
  //serverNum is generated by computer
  return(
    <>
    <div className='app'>
        <div className='head'>
            <label>Guess the number between 1 to 10</label>
        </div>
        <input id='term' type='text' name='term' onChange={handleInputvalue}/>
        {/* passing the props for Answer component*/}
        <Answer serverNum={serverNum} term={term}/>
    </div>
    </>
  )
}

export default App;
